"""
VisCache_RepostFromEXR.py — Repost from raw EXRs / per-variant PNGs, not CSV.

Sibling to VisCache_Repostprocess.py which walks stats.csv. That misses
variants whose CSV rows were pruned but whose raw/ EXR archives still
exist. This script walks per-variant `<scene>/s_*_r1c1_accum_render.png`
(generated by stitch_plate, encoding all run-config dimensions in the
filename) and calls `postprocess_variant` for every one that has a
matching raw EXR. Recovers full sweep matrices for steps where the CSV
was gutted.

Filename pattern (encoded by `run_variants` → `stitch_plate`):
    s_<frames>_x<eff_spp>_<wf>o<wr>o<NxN>_<resXxresY>_<variant>_r1c1_accum_render.png

Usage:
    runtime/pythondist/python.exe scripts/VisCache_RepostFromEXR.py [step ...]
    # default: all steps with at least one <scene>/<...>r1c1_accum_render.png
"""
import os, sys, glob, re

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Match the scene-subdir per-variant PNG written by stitch_plate.
# Greedy variant matching backstops on "_r1c1_accum_render.png".
_PNG_RE = re.compile(
    r'^s_(\d+)_x(\d+)_(\d+)o(\d+)o(\d+)x\d+_(\d+x\d+)_(.+)_r1c1_accum_render\.png$'
)

_project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault("PROJECT_ROOT", _project_root)
os.chdir(os.path.join(_project_root, "runtime"))

from VisCache_LadderCommon import (
    postprocess_variant, plot_overviews, copy_summary_to_root,
)


def _repost_step(step):
    step_dir = os.path.join("captures", "ladder", step)
    if not os.path.isdir(step_dir):
        print(f"[repost-exr] step {step}: no dir, skip")
        return

    scene_dirs = sorted(d for d in glob.glob(os.path.join(step_dir, "*"))
                         if os.path.isdir(d) and os.path.isdir(os.path.join(d, "raw")))
    if not scene_dirs:
        print(f"[repost-exr] step {step}: no scene dirs with raw/ archive")
        return

    count = 0
    for scene_path in scene_dirs:
        scene = os.path.basename(scene_path)
        raw_dir = os.path.join(scene_path, "raw")

        # Enumerate every (frames, eff_spp, wf, wr, bayer, res, variant)
        # combination present in this scene. Per-variant PNGs are the
        # authoritative source — they were emitted at capture time.
        for png in sorted(glob.glob(os.path.join(scene_path, "s_*_r1c1_accum_render.png"))):
            m = _PNG_RE.match(os.path.basename(png))
            if not m:
                continue
            frames       = int(m.group(1))
            eff_spp      = int(m.group(2))
            warmup_first = int(m.group(3))
            warmup_run   = int(m.group(4))
            bayer_n      = int(m.group(5))
            res_tag      = m.group(6)
            variant      = m.group(7)

            # Raw EXR for this variant must exist (different SPPs share
            # a variant, so any one matching .exr is enough — postprocess
            # picks the one matching `spp=`).
            raw_glob = os.path.join(raw_dir, f"{variant}.*.exr")
            if not glob.glob(raw_glob):
                continue

            # Reconstruct the prefix used by postprocess_variant. The
            # CSV-walker (VisCache_Repostprocess.py) recovers prefix as
            # `key.removeprefix(scene + "_") + "_"` which BAKES variant
            # into the prefix — append_stats_csv keys on `<scene>_<prefix>`
            # so omitting variant from prefix would collapse all variants
            # of one (scene, spp) into the same CSV row.
            raw_spp = max(1, eff_spp // max(1, frames))
            prefix  = (f"s_{frames}_x{eff_spp}_"
                       f"{warmup_first}o{warmup_run}o{bayer_n}x{bayer_n}_"
                       f"{res_tag}_{variant}_")

            print(f"[repost-exr] step {step} {scene} {variant} (frames={frames}, eff_spp={eff_spp})")
            postprocess_variant(
                step, scene, scene_path, prefix, variant,
                frames=frames, spp=raw_spp,
                warmup_first=warmup_first, warmup_run=warmup_run, bayer_n=bayer_n,
            )
            count += 1

    print(f"[repost-exr] step {step}: reprocessed {count} variants")
    if count > 0:
        plot_overviews(step)
        copy_summary_to_root(step)


steps = sys.argv[1:] if len(sys.argv) > 1 else None
if steps is None:
    pattern = os.path.join(_project_root, "runtime", "captures", "ladder", "*")
    steps = sorted(os.path.basename(p) for p in glob.glob(pattern)
                    if os.path.isdir(p) and not os.path.basename(p).startswith("archive_"))

for step in steps:
    _repost_step(step)

print("[repost-exr] done")
